### ISSUE TITLE
Issue tracking for release

### ISSUE THREAD

**Issue by ChrisRackauckas** [JuliaDiffEq/DiffEqOnline#8]
I'll put out a blog post on this and start promoting it, but there's a few things left to tackle:

- [x] Response time https://github.com/JuliaDiffEq/DiffEqOnline/issues/7
- [x] `vars` option for plotting
- [x] `Rosenbrock23` algorithm option
- [x] Error reports https://github.com/JuliaDiffEq/DiffEqOnline/issues/4
- [x] About page
- [x] Store settings in url: https://github.com/JuliaDiffEq/DiffEqOnline/issues/3
- [x] Input sanitation: https://github.com/JuliaDiffEq/DiffEqOnlineServer/issues/6
- [x] Nothing is complete without a favicon
- [x] Error checking on initial conditions #10

I think that's enough to launch, and other things like exposing Sundials algorithms could be done later (and it'll probably make some more people interested in helping!)

**Comment by amellnik** [comment]
Looks good, added two and about to knock off one.

**Comment by ChrisRackauckas** [comment]
>Nothing is complete without a favicon

Smart man.

**Comment by ChrisRackauckas** [comment]
There's a favicon for JuliaDiffEq:

https://github.com/JuliaDiffEq/juliadiffeq.github.io/blob/master/favicon.png

Just need to get the web server to use it.

**Comment by ChrisRackauckas** [comment]
I find that I am sometimes able to hit the memory quota. Maybe because maxiters is too high on the divergent runs? You can check with:

```
dx = a*x - b*x*y - 2x
dy =- d*x*y
```

**Comment by ChrisRackauckas** [comment]
Well I had a whole lot done and was about to call it a night, but then the last front-end that I sent to the server won't stop spinning. Could you take a look at it? I can't seem to find out what is up.

But the current state is really good (sans this spinning issue). It is responsive, I can do cool 3D Lorenz equation plots, equations which explode stop earlier and throw an appropriate error, the about page is filled out, etc.

**Comment by ChrisRackauckas** [comment]
Is there some kind of delay when updating the frontend? It seems that every time when I push to the server it goes down for a bit (at least, it went down for a bit and was up when I woke up, looks like it's doing it again, don't know if you did something in between)

**Comment by amellnik** [comment]
Yeah, there's some initial dyno boot time in addition to the julia startup costs.  I haven't pushed anything to it in the last day or so.  There might be something else going on too -- @abahm mentioned that it was down for him at some point when neither of us was pushing anything.  I'll start looking into the logs and dashboard.

**Comment by amellnik** [comment]
Ah whoops I misread this the first time.  I think Alan's issue was related to the back end.

**Comment by ChrisRackauckas** [comment]
The first plot does have a startup time, but any plot after that (for any user) should be snappy. So we just got to make sure we run it once after deployment... or maybe there's a way to just call the solve function once to force compilation for everything?

**Comment by ChrisRackauckas** [comment]
I am planning to upgrade right before release. I usually get around 500 blog views on a post day, but I assume that this will have an even wider reach (it's fun!), so we may want to be prepared for at least a 1000 user  day. After a week it'll calm down and we can then adjust it back down. I'll front the cost.

**Comment by amellnik** [comment]
Sure, if it really takes off I can also pitch in.  We can bake a call to `solveit(...)` with default parameters into the main script before `@sync serve(...)`.

**Comment by ChrisRackauckas** [comment]
>We can bake a call to solveit(...) with default parameters into the main script before @sync serve(...).

That sounds like the right idea.

I just put a PR in for a tag of OrdinaryDiffEq.jl. It also includes something that should make the init dt special handling no longer necessary. If we just go with the plot recipe and this is gone, we can scrap a lot of the code I added last night but keep the benefits. I'll test it out soon.

**Comment by amellnik** [comment]
Re new item -- I'll work this in soon, but probably not blocking for release.  

![image](https://cloud.githubusercontent.com/assets/7132414/22002175/8c9a99c2-dbfe-11e6-8e9a-ee3fcad1e88a.png)

**Comment by ChrisRackauckas** [comment]
Is this good for now?

**Comment by amellnik** [comment]
Yep!  The heroku timeout returns a 503 response but without the proper access headers so the client ignores it (and treats it as a 0 response for some reason) but I think I'm also handling that case now.  

I have a few minor tweaks I want to make to improve the layout on mobile devices, but I don't think it's blocking.

**Comment by ChrisRackauckas** [comment]
Alright, I upped the plan to take a potential initial hit. Let's see what happens?

**Comment by amellnik** [comment]
Sounds good!

(Please excuse brevity and errors, sent from a mobile device.)
